name: Grosso Antonio
title: Grosso Antonio
markdown: kramdown
exclude: ["node_modules", "gulpfile.js", "package.json", "readme.md"]
url: "https://grossoantonio.it" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap

sass:
  sass_dir: _sass # Default location for SCSS partials
  style: compressed # Optional: set output style for CSS

nav:
  - title: "Home"
    url: /index.html
  - title: "Azienda"
    url: /company.html
  - title: "Cilindri Fotoincisi"
    url: /photoengraved-rollers.html
  - title: "Catalogo Cilindri"
    url: /rollers-catalog.html
  - title: "Carta Smeriglio"
    url: /buffing-paper.html
  - title: "Prodotti"
    url: javascript:void(0)
    sub-nav:
      - title: Gomme
        url: /rubbers.html
      - title: Feltri
        url: /felts.html
      - title: Manicotto per tamponatrici
        url: /carpet-belt.html
      - title: Tappeto per Dinavac
        url: /dinavac-carpet.html
      - title: Pedana di sollevamento
        url: /lift-tables.html
      - title: Cabina Luci
        url: /colour-hatching-cabinets.html
  - title: Pezzi di ricambio
    url: /spare-parts.html
  - title: Macchinari Nuovi
    url: /new.html
  - title: Macchinari Usati
    url: /used.html
  - title: Contatti
    url: /contacts.html

nav_en:
  - title: "Home"
    url: /en/index.html
  - title: "Company"
    url: /en/company.html
  - title: "Photoengraved Rollers"
    url: /en/photoengraved-rollers.html
  - title: "Rollers Catalog"
    url: /en/rollers-catalog.html
  - title: "Buffing Paper"
    url: /en/buffing-paper.html
  - title: "Products"
    url: javascript:void(0)
    sub-nav:
      - title: Rubbers
        url: /en/rubbers.html
      - title: Felts
        url: /en/felts.html
      - title: Carpet Belt
        url: /en/carpet-belt.html
      - title: Dinavac Carpet
        url: /en/dinavac-carpet.html
      - title: Lift Tables
        url: /en/lift-tables.html
      - title: Colour Hatching Cabinets
        url: /en/colour-hatching-cabinets.html
  - title: Spare Parts
    url: /en/spare-parts.html
  - title: New Machinery
    url: /en/new.html
  - title: Second Hand Machines
    url: /en/used.html
  - title: Contacts
    url: /en/contacts.html

banner_cta_it_1: Stai cercando un ricambio/accessorio specifico per conceria? Inviaci la tua richiesta
banner_cta_it_2: Saremo pronti a fornirti quanto richiesto nel più breve tempo possibile.
banner_cta_en_1: Are you looking for a specific spare part/accessory for tannery? Send us your request
banner_cta_en_2: We will be ready to provide you with what you request as soon as possible.
